Document: p-star
Title: Debian p-star Manual
Author: <insert document author here>
Abstract: This manual describes what p-star is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/p-star/p-star.sgml.gz

Format: postscript
Files: /usr/share/doc/p-star/p-star.ps.gz

Format: text
Files: /usr/share/doc/p-star/p-star.text.gz

Format: HTML
Index: /usr/share/doc/p-star/html/index.html
Files: /usr/share/doc/p-star/html/*.html
